name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  backend:
    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
          TZ: Asia/Tokyo
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      valkey:
        image: valkey/valkey:8-alpine
        env:
          KVS_PASSWORD: password
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli -a password ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./backend/go.mod
          cache-dependency-path: ./backend/go.sum

      - uses: bufbuild/buf-setup-action@v1

      - name: Install dependencies
        run: cd backend && go mod download

      - name: Verify all files are up to date
        run: |
          make -C ./backend generate

          if [[ $(git status --porcelain) ]]; then
            echo "Error: There are uncommitted changes in the working directory after generation."
            git diff
            exit 1
          fi

      - name: Verify all files are formatted
        run: |
          make -C ./backend lint-fix

          if [[ $(git status --porcelain) ]]; then
            echo "Error: There are uncommitted changes in the working directory after lint."
            git diff
            exit 1
          fi

      - name: Inject .env
        run: envsubst < .env.example > .env

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.3

      - name: Execute localstack init script
        run: ./localstack/init.sh

      - name: Test
        run: make test

  frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: '24.13.1'

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Type check
        run: cd frontend && npm run typecheck

      - name: Verify all files are formatted
        run: |
          cd frontend && npm run lint:fix

          if [[ $(git status --porcelain) ]]; then
            echo "Error: There are uncommitted changes in the working directory after check."
            git diff
            exit 1
          fi
